In [1]:
import numpy as np

## Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
arr = np.linspace(2,50,3)
print(arr)

[ 2. 26. 50.]


## Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
#initializing empty array
arr1, arr2 = [], []

#accepting 2 list from user
print("Enter 5 element of List 1:")
for i in range(5):
    n = int(input())
    arr1.append(n)
print()

print("Enter 5 element of List 2:")
for i in range(5):
    n = int(input())
    arr2.append(n)  

print()

#display of entered list
print("First :" + str(arr1))
print("Second :" + str(arr2))
print()

#converting into numpy array
np_arr1 = np.array(arr1)
np_arr2 = np.array(arr2)

#concantinating both the array
arr = np.concatenate((np_arr1, np_arr2))
print("Merged array:" + str(arr))
print()

#sorting the array
arr = np.sort(arr)
print(arr)

Enter 5 element of List 1:
3
4
2
5
1

Enter 5 element of List 2:
7
6
8
0
9

First :[3, 4, 2, 5, 1]
Second :[7, 6, 8, 0, 9]

Merged array:[3 4 2 5 1 7 6 8 0 9]

[0 1 2 3 4 5 6 7 8 9]


## Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr_1d = np.arange(4)
print("    Fisrt nd array: ")
print(arr_1d)
print("    Dimension: " + str(arr_1d.ndim))
print("    Size: " + str(arr_1d.size) )
print()

arr_2d = np.arange(16).reshape(4,4)
print("    Second nd array: ")
print(arr_2d)
print("    Dimension: " + str(arr_2d.ndim))
print("    Size: " + str(arr_2d.size) )

print()
arr_3d = np.arange(24).reshape(3,2,4)
print("    Third nd array: ")
print(arr_3d)
print("    Dimension: " + str(arr_3d.ndim))
print("    Size: " + str(arr_3d.size) )

    Fisrt nd array: 
[0 1 2 3]
    Dimension: 1
    Size: 4

    Second nd array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
    Dimension: 2
    Size: 16

    Third nd array: 
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
    Dimension: 3
    Size: 24


## Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
#to convert 1D into 2D... observ the following example
array = np.arange(16)

#using np.newaxis
print("np.newaixs")
print(array[np.newaxis, :8]) #here 8 is the number of columns
print(array[:4, np.newaxis]) #here 4 in the number of rows
print()

#using np.expand_dims
print("np.expand_dims")
print(np.expand_dims(array, axis=(0)))
print(np.expand_dims(array[:5], axis=1))

np.newaixs
[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]

np.expand_dims
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[0]
 [1]
 [2]
 [3]
 [4]]


## Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
arr_1 = np.random.randn(9).reshape(3,3)
arr_2 = np.random.randn(9).reshape(3,3)

print("Matrix 1:")
print(arr_1)
print()

print("Matrix 2:")
print(arr_2)
print()

print("Horizontally Stacking the Matrices: ")
print(np.hstack((arr_1, arr_2)))
print()

print("Vertically Stacking the Matrices:")
print(np.vstack((arr_1, arr_2)))


Matrix 1:
[[ 0.30303593  1.49917074  1.62404603]
 [ 1.3505474   0.30140652 -1.25537326]
 [ 0.67757006 -0.20091139 -0.47122778]]

Matrix 2:
[[-1.44577927  0.97495242  0.69205118]
 [ 0.19827315  0.80597425  0.96700968]
 [-0.21740385  1.52242276  0.64825238]]

Horizontally Stacking the Matrices: 
[[ 0.30303593  1.49917074  1.62404603 -1.44577927  0.97495242  0.69205118]
 [ 1.3505474   0.30140652 -1.25537326  0.19827315  0.80597425  0.96700968]
 [ 0.67757006 -0.20091139 -0.47122778 -0.21740385  1.52242276  0.64825238]]

Vertically Stacking the Matrices:
[[ 0.30303593  1.49917074  1.62404603]
 [ 1.3505474   0.30140652 -1.25537326]
 [ 0.67757006 -0.20091139 -0.47122778]
 [-1.44577927  0.97495242  0.69205118]
 [ 0.19827315  0.80597425  0.96700968]
 [-0.21740385  1.52242276  0.64825238]]


## Questions 6:
How to get unique items and counts of unique items?

In [7]:
array = np.array([1,3,6,7,2,9,1,5,3,1,6,3,9,5])
print("List:" + str(array))
print()
unique, cnt = np.unique(array, return_counts = True)
print("Unique values are: ")
print(unique)
print()
print("And their occurances are: ")
print(cnt)


List:[1 3 6 7 2 9 1 5 3 1 6 3 9 5]

Unique values are: 
[1 2 3 5 6 7 9]

And their occurances are: 
[3 1 3 2 2 1 2]


END OF ASSIGNMENT 3